name: Publish Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEMETRY_RELEASE: stargazer-qq-${{ github.sha }}
    steps:
      - uses: actions/checkout@master
      - name: Publish to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: photonquantum/stargazer-qq
          username: ${{ secrets.PQ_DOCKER_USERNAME }}
          password: ${{ secrets.PQ_DOCKER_PASSWORD }}
          buildargs: TELEMETRY_RELEASE
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: suiseicn
          SENTRY_PROJECT: stargazer-qq
        with:
          tagName: ${{ env.TELEMETRY_RELEASE }}
          environment: prod
